### ISSUE TITLE
[Review] Improve clarity in user experience

### ISSUE THREAD

**Issue by unfazing** [AY2223S2-CS2103T-W11-3/tp#151]
- [x] Allow user to unflip cards #178 
- [x] Do not immediately move to next card upon marking correct #178 
- [x] Include nav guide into side bar #179 
- [x] Reconsider User Commands for flip, next, prev, correct, wrong #179 
- [x] Add different colour for flipped card #181 
- [x] Style nav guide

**Comment by junianob** [comment]
User commands may need to be changed. Current implementation  of using [ ] ; '  symbols may not be very intuitive. Changing to a more familiar layout (WASD for example) or displaying the commands in the UI will help.
